### ISSUE TITLE
TTS not using GPU (cuda)

### ISSUE THREAD

**Issue by roryeckel** [speaches-ai/speaches#255]
I am using the container for both TTS and STT. STT is using the GPU as expected. However, TTS is not.
Here is my compose:
```
services:
    speaches:
        container_name: speaches
        image: ghcr.io/speaches-ai/speaches:latest-cuda
        restart: unless-stopped
        ports:
          - 8080:8000
        environment:
            - WHISPER__MODEL=Systran/faster-distil-whisper-large-v3
        volumes:
            - ./huggingface-hub:/home/ubuntu/.cache/huggingface/hub
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
        memswap_limit: 0g
        runtime: nvidia
```

When I make a request to the Kokoro model for the first time, this appears in my logs:

`/home/ubuntu/speaches/.venv/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'`

It is also using the CPU
